name: Android CI and Release

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      fail_fast: false
